; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=stubv32 < %s | FileCheck %s

target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
target triple = "stubv32"

define i32 @and(i32 %a, i32 %b) {
; CHECK-LABEL: and:
; CHECK:       # %bb.0:
; CHECK-NEXT:    and a0, a0, a1
; CHECK-NEXT:    and a0, a0, 42
; CHECK-NEXT:    ret
  %c = and i32 %a, %b
  %d = and i32 %c, 42
  ret i32 %d
}
