; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=stubv32 -stop-after finalize-isel < %s | FileCheck %s

define i32 @ld(ptr %p) {
  ; CHECK-LABEL: name: ld
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[LW:%[0-9]+]]:gpr = LW [[COPY]], 16 :: (load (s32) from %ir.addr)
  ; CHECK-NEXT:   [[LW1:%[0-9]+]]:gpr = LW [[COPY]], 0 :: (load (s32) from %ir.p)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD killed [[LW1]], killed [[LW]]
  ; CHECK-NEXT:   $x10 = COPY [[ADD]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  %x = load i32, ptr %p
  %addr = getelementptr i32, ptr %p, i32 4
  %y = load i32, ptr %addr
  %z = add i32 %x, %y
  ret i32 %z
}
