; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=stubv32 < %s | FileCheck %s

define i32 @ld(ptr %p) {
; CHECK-LABEL: ld:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lw a1, 16(a0)
; CHECK-NEXT:    lw a0, (a0)
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    ret
  %x = load i32, ptr %p
  %addr = getelementptr i32, ptr %p, i32 4
  %y = load i32, ptr %addr
  %z = add i32 %x, %y
  ret i32 %z
}
