; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=stubv32 --stop-after finalize-isel < %s | FileCheck %s

define void @st(ptr %p, i32 %v) {
  ; CHECK-LABEL: name: st
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   SW [[COPY]], [[COPY1]], 4 :: (store (s32) into %ir.a)
  ; CHECK-NEXT:   SW [[COPY]], [[COPY1]], 0 :: (store (s32) into %ir.p)
  ; CHECK-NEXT:   PseudoRET
  store i32 %v, ptr %p
  %a = getelementptr i32, ptr %p, i32 1
  store i32 %v, ptr %a
  ret void
}
