; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=stubv32 < %s | FileCheck %s

define void @st(ptr %p, i32 %v) {
; CHECK-LABEL: st:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sw a1, 4(a0)
; CHECK-NEXT:    sw a1, (a0)
; CHECK-NEXT:    ret
  store i32 %v, ptr %p
  %a = getelementptr i32, ptr %p, i32 1
  store i32 %v, ptr %a
  ret void
}
