; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=stubv32 --stop-after finalize-isel < %s | FileCheck %s

target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
target triple = "stubv32"

define i32 @xor(i32 %a, i32 %b) {
  ; CHECK-LABEL: name: xor
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT: liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[XOR:%[0-9]+]]:gpr = XOR [[COPY1]], [[COPY]]
  ; CHECK-NEXT:   [[XORI:%[0-9]+]]:gpr = XORI killed [[XOR]], 12
  ; CHECK-NEXT: $x10 = COPY [[XORI]]
  ; CHECK-NEXT: PseudoRET implicit $x10

  %c = xor i32 %a, %b
  %d = xor i32 %c, 12
  ret i32 %d
}

